### ISSUE TITLE
renderContent highlightSyntax example error

### ISSUE THREAD

**Issue by mcgrealife** [Aeolun/react-diff-viewer-continued#10]
When attempting to add syntax highlighting, I encounter these errors:

## Prism.highlight() interface now requires 3 args, not 2:
- the docs show `__html: highlight(str, Prism.languages.javascript)`, however, it looks like the most recent interface has 3 args:
![highlight-interface](https://user-images.githubusercontent.com/11381911/206353737-c0158964-a602-42be-9026-ede8c8ba0ed2.png)
- easily resolved with `__html: Prism.highlight(str, Prism.languages.javascript, 'javascript')`

## Prism.highlight() arg0 `str` undefined:
![highlight-error-message-arg0-undefined](https://user-images.githubusercontent.com/11381911/206354145-81c9c052-69a6-4911-bbf3-f309e50af407.png)
- passing a string directly to the highlight function arg0 (e.g. `__html: Prism.highlight(oldCode, Prism.languages.javascript, 'javascript')` but then this shows the oldCode on both sides of the splitView!

_Any advice is appreciated!_

#### packages:
"react": "18.2.0",
"react-diff-viewer-continued": "^3.2.3",
 "prismjs": "^1.29.0",
"@types/prismjs": "^1.26.0",

**Comment by xino1010** [comment]
```typescript
const FileDiffs = () => {
  const highlightSyntax = (str: string) =>
    !str ? (
      <div />
    ) : (
      <pre
        style={{ display: "inline" }}
        dangerouslySetInnerHTML={{
          __html: Prism.highlight(
            str,
            Prism.languages.javascript,
            "javascript"
          ),
        }}
      />
    );
  return (
    <ReactDiffViewer
      oldValue={oldCode}
      newValue={newCode}
      splitView={true}
      renderContent={highlightSyntax}
    />
  );
};
```

**Comment by mcgrealife** [comment]
@xino1010 ah! check for undefined – of course. Much appreciated :)
