### ISSUE TITLE
How to select desired text in splitview?

### ISSUE THREAD

**Issue by LifeIsStrange** [Aeolun/react-diff-viewer-continued#15]
In splitview, a user will often want either to copy all the text of the left view, or all the text of the right view.
Unfortunately, contrary to e.g. Github diff, when we select text after a paragraph it begins to also select the other side of the splitview, which is undesired.
For example my app needs to show an old version and a new version of a SQL query. The user wants to select chunks or all of the previous query, or of the new one, not a mixed version of both..

How to fix the selection?
The html structure is mixed which seems to prevents a CSS solution for selection.

**Comment by Aeolun** [comment]
Yeah, right now the way the diff is displayed is with a table. If we need to split the selection, that would need to happen by making the two sides separate. The table is convenient for layout, since lines always align, but it's probably not impossible to do it with two separate div's instead.

**Comment by Pangamma** [comment]
I am also interested in a fix for this.

**Comment by mdpx** [comment]
seems this is reverted, any plan for another fix?
