### ISSUE TITLE
diff not on a same line

### ISSUE THREAD

**Issue by TipicultBiomassa** [Aeolun/react-diff-viewer-continued#25]
First image is how it looks on my page and second is how it looks on your website. Why on my page diff is not on the same line
<img width="1336" alt="image" src="https://github.com/Aeolun/react-diff-viewer-continued/assets/48147673/e18a8e19-0033-4a0b-9d77-cb7dcdfb3478">
<img width="1171" alt="image" src="https://github.com/Aeolun/react-diff-viewer-continued/assets/48147673/d0d75877-04e6-4782-a2e5-4df14c020fdc">

**Comment by Aeolun** [comment]
@TipicultBiomassa The only difference I see here is the extra gutter that the one on the website has. Could you post your code here so I can investigate when I get the chance?
