### ISSUE TITLE
Setting extraLinesSurroundingDiff to 0 hides the top skipped lines indicator

### ISSUE THREAD

**Issue by psmolaga** [Aeolun/react-diff-viewer-continued#29]
Hi Guys,

I have observed that setting `extraLinesSurroundingDiff` props to `0` hides the top skipped lines indicator.

Reproduction: https://stackblitz.com/edit/stackblitz-starters-wsteyt?file=src%2FApp.tsx

**Comment by Aeolun** [comment]
Thanks for reporting that. I’ll have a look.

**Comment by psmolaga** [comment]
@Aeolun thank you!
