### ISSUE TITLE
Getting error 'Module not found: Error: Can't resolve +'react-diff-viewer-continued' ' after updating to 3.3.0

### ISSUE THREAD

**Issue by greymind** [Aeolun/react-diff-viewer-continued#31]
I had to add the dependency explicitly and set to 3.2.6 to fix my builds. Not sure which package was using it though. Perhaps payload cms?

**Comment by samuelcole** [comment]
same, my guess is this line: https://github.com/Aeolun/react-diff-viewer-continued/commit/c4b317af31935740dd9fe8ac526ceb8fd63db6a9#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R15

**Comment by leonbloy** [comment]
Same.
Breaks with vite and node 18.18.2

**Comment by Aeolun** [comment]
Apologies all. That'll teach me to not immediately update the newly released library in my own applications. Thanks for the report!
