### ISSUE TITLE
Version 4.0.0 Cannot find module 'react-diff-viewer-continued'

### ISSUE THREAD

**Issue by Tabofa** [Aeolun/react-diff-viewer-continued#34]
Upgrading to 4.0.0 generates error "TS2307: Cannot find module 'react-diff-viewer-continued' or its corresponding type declarations."

- in the node_modules folder the lib-folder is missing (is there in previous versions)
- on npm page the lib-folder is missing (is there in previous versions)

Seems it's shipping without source code.
![image](https://github.com/Aeolun/react-diff-viewer-continued/assets/8895061/13827622-bf23-4412-8394-e5790598f8d8)

**Comment by Aeolun** [comment]
@Tabofa A new version 4.0.1 has been published that resolves this issue.

**Comment by Tabofa** [comment]
Now it works!
Just want to add that I think it's awesome what you're doing! Cudos!
