### ISSUE TITLE
Discussion- Is it possible to compare more than 2 variables ?

### ISSUE THREAD

**Issue by ObaidAshiq** [Aeolun/react-diff-viewer-continued#45]
I was wondering if we can extend the cababiliti to diff not just 2 things, but say more things
Concern i have, how much it would impact performance ?

**Comment by Aeolun** [comment]
I've thought about this before, but I don't think the diff algorithm is really made to compare more than two things at a time. As such it would be too much of an effort, and beyond the scope of where I'm willing to take this. If someone has a different 'triple or more' diff library, then maybe the display can be implemented.
